### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

# 🏃 NumPy Tricks — 25 Useful Functions

**Topic:** 06.03 · **Level:** 🟠 Intermediate · **Type:** THEORY + CODE

## 📖 Session ka format

Har trick ke liye: definition → `# code` cell me example

**Quick menu:**

| Function | Kaam |
|---|---|
| `np.sort` | sorted copy |
| `np.append` | end me add |
| `np.concatenate` | arrays jodo |
| `np.unique` | duplicates hataye |
| `np.where` | condition-based select/replace |
| `np.argmax/argmin` | max/min ka index |
| `np.cumsum/cumprod` | running sum/product |
| `np.percentile` | percentile |
| `np.histogram` | frequency bins |
| `np.corrcoef` | correlation |
| `np.isin` | membership filter |
| `np.flip` | reverse |
| `np.put` | element replace |
| `np.delete` | element hatao |
| set funcs | union/intersect/diff |
| `np.clip` | values limit |

Baaki (swapaxes, uniform, tile, repeat, allclose) ending me hai.
Har ek me `axis` ki role hamesha yaad — `0` columns, `1` rows.

In [114]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [115]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

## 🔬 Deep Dive : np.sort — sorting arrays

```python
a = np.random.randint(1,100,15)
np.sort(a)[::-1]       # sorted descending
np.sort(b, axis=0)     # sort along columns
```

- np.sort — **returns sorted copy** (original untouched)
- vs a.sort() — in place, returns None
- `[::-1]` on result — descending
- axis — sort direction (0 cols, 1 rows)
- 1D default ascending
- string/object sort possible
- stable sort option kind arg
- unique + sort linkage
- np.argsort — indices of sorted (for ranking)
- Real: ranking, data prep

In [120]:
np.sort(a)[::-1]

array([94, 92, 78, 68, 53, 50, 38, 37, 30, 28, 21, 11,  9,  5,  2])

In [119]:
np.sort(b,axis=0)

array([[ 8, 18,  2,  6],
       [12, 52, 31,  7],
       [29, 63, 42,  9],
       [38, 71, 44, 55],
       [40, 87, 47, 72],
       [61, 93, 83, 85]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

## 🔬 Deep Dive : np.append

```python
np.append(a, 200)                    # add element at end (copy!)
np.append(b, np.random.random((b.shape[0],1)), axis=1)  # add column
```

- Append — **returns new array** (costly; copy)
- axis=None → flatten + append
- single element append
- axis=0 rows append (must shape match)
- axis=1 add column
- Original unchanged
- For repeated appends prefer lists then np.array
- dims alignment required
- int/float coercion to common dtype
- panel note: append can be slow bulk — plan

In [122]:
# code
np.append(a,200)

array([ 11,  53,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21, 200])

In [123]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [126]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[12.        , 52.        , 42.        ,  6.        ,  0.22006275],
       [29.        , 18.        , 47.        , 55.        ,  0.81740634],
       [61.        , 93.        , 83.        ,  9.        ,  0.89146072],
       [38.        , 63.        , 44.        , 85.        ,  0.84519124],
       [ 8.        , 87.        , 31.        , 72.        ,  0.24007274],
       [40.        , 71.        ,  2.        ,  7.        ,  0.48056374]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [127]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


## 🔬 Deep Dive : np.concatenate

```python
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
np.concatenate((c,d), axis=0)   # stack rows → (4,3)
np.concatenate((c,d), axis=1)   # stack cols → (2,6)
```

- concatenate((a,b,...), axis) — join along axis
- axis=0 → rows (samples), axis=1 → cols (features)
- Must match along other axes
- List/tuple of arrays
- vs hstack/vstack convenient wrappers
- Efficient bulk row combine
- Dataframes merge same concept (pandas)
- returns new array
- Use for matrix assembly

In [128]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [129]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [130]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

## 🔬 Deep Dive : np.unique — distinct values

```python
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)     # [1 2 3 4 5 6] — sorted unique
```

- Returns sorted unique elements (copy)
- return_counts=True → frequency
- return_index → first occurrence positions
- 2D: axis param unique rows
- Categories / one-hot prep
- vs set analog: set(e) 
- freq distribution fast
- `np.unique(a, return_counts=True)` → values, counts
- for pandas: value_counts later
- data cleaning for duplicates

In [131]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [134]:
# code
a.shape

(15,)

## 🔬 Deep Dive : np.expand_dims — add axis

```python
a.shape                     # (15,)
np.expand_dims(a, axis=0).shape   # (1,15) — row vector
np.expand_dims(a, axis=1)         # (15,1) — column vector
```

- Add singleton dimension at given axis
- axis=0 → (1,N); axis=1 → (N,1)
- Needed: broadcasting, ML batch dims
- Broadcasting: (N,1) + (M,) interactions
- transpose pairing
- np.newaxis alias: `a[None, :]`, `a[:, None]`
- ML: model input (1, features) shape
- reshape(-1,1) does same column trick
- Cheap view — no copy
- Important data shape manipulation

In [135]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [137]:
np.expand_dims(a,axis=1)

array([[11],
       [53],
       [28],
       [50],
       [38],
       [37],
       [94],
       [92],
       [ 5],
       [30],
       [68],
       [ 9],
       [78],
       [ 2],
       [21]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [138]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

## 🔬 Deep Dive : np.where — conditional select

```python
a
np.where(a > 50)          # INDICES of True positions (tuple)
np.where(a > 50, 0, a)    # replace: cond true → 0 else a
np.where(a % 2 == 0, 0, a)  # even→0, odd keep
```

- Two modes:
  1. `np.where(cond)` → indices (tuple of arrays)
  2. `np.where(cond, x, y)` → array: True→x, False→y
- Index mode: `a[np.where(a>50)[0]]` ≈ mask
- Fancy: positional finding
- Vectorized if/else — no loop!
- replace values based on condition
- Nested: np.select / boolean combo
- pandas .where similar
- Critical utility for conditional ops

In [139]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  6,  7, 10, 12]),)

In [140]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([11,  0, 28, 50, 38, 37,  0,  0,  5, 30,  0,  9,  0,  2, 21])

In [141]:
np.where(a%2 == 0,0,a)

array([11, 53,  0,  0,  0, 37,  0,  0,  5,  0,  0,  9,  0,  0, 21])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [142]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

## 🔬 Deep Dive : np.argmax / np.argmin

```python
np.argmax(a)          # index of max value (flat)
np.argmax(b, axis=0)  # max per column → row index
np.argmax(b, axis=1)  # per row → col index
np.argmin(a)
```

- Returns INDEX of max/min value (not value)
- axis variant along dimension
- ML: argmax(softmax probs) → predicted class
- tie → first occurrence
- Get value: `a[np.argmax(a)]`
- axis=0 → for each col which row max
- axis=1 → for each row which col max
- model predictions = argmax logic
- essential deep learning metric

In [143]:
np.argmax(a)

6

In [145]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [144]:
np.argmax(b,axis=0)

array([2, 2, 2, 3])

In [146]:
np.argmax(b,axis=1)

array([1, 3, 1, 3, 1, 1])

In [148]:
# np.argmin
np.argmin(a)

13

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [149]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

## 🔬 Deep Dive : np.cumsum / np.cumprod

```python
np.cumsum(a)         # running sum: [x0, x0+x1, ...]
np.cumsum(b, axis=1) # cumulative along rows
np.cumprod(a)
```

- cumsum — cumulative (running) sum
- cumprod — running product
- axis variants along dim
- Real: daily balances, running scores
- array[i] = sum(a[:i+1])
- cumprod use probabilities chains
- compare range-less vs normal functions
- 2D axis controll
- numpy daily time series

In [150]:
np.cumsum(a)

array([ 11,  64,  92, 142, 180, 217, 311, 403, 408, 438, 506, 515, 593,
       595, 616])

In [151]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [154]:
np.cumsum(b,axis=1)

array([[ 12,  64, 106, 112],
       [ 29,  47,  94, 149],
       [ 61, 154, 237, 246],
       [ 38, 101, 145, 230],
       [  8,  95, 126, 198],
       [ 40, 111, 113, 120]])

In [152]:
np.cumsum(b)

array([  12,   64,  106,  112,  141,  159,  206,  261,  322,  415,  498,
        507,  545,  608,  652,  737,  745,  832,  863,  935,  975, 1046,
       1048, 1055])

In [156]:
# np.cumprod
np.cumprod(a)

array([                  11,                  583,                16324,
                     816200,             31015600,           1147577200,
               107872256800,        9924247625600,       49621238128000,
           1488637143840000,   101227325781120000,   911045932030080000,
       -2725393596491966464, -5450787192983932928, -3786066610405281792])

In [155]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [157]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

## 🔬 Deep Dive : np.percentile — quantiles

```python
np.percentile(a, 50)     # median (50th percentile)
np.median(a)             # same for even-50
```

- percentile(data, q) — value below q% of data
- q=50 → median
- q=25/75 → quartiles (IQR)
- Multi q: np.percentile(a, [25,50,75])
- np.median alias for q=50
- np.quantile scaled 0..1
- Robust stats (outliers resistance)
- Box plots derive from percentiles
- Very common EDA metric

In [160]:
np.percentile(a,50)

37.0

In [161]:
np.median(a)

37.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [162]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

## 🔬 Deep Dive : np.histogram

```python
np.histogram(a, bins=[0,50,100])
# → counts in each bin + bin edges
```

- Frequency count into bins
- bins edges define ranges
- Returns (hist_values, bin_edges)
- bins: int count or list of edges
- density=True → probability
- Hist plots built on this (plt.hist)
- Data distribution visualization data
- bin pick matters (interpretation)
- vs np.bincount (int bins only)
- EDA: understand distribution

In [164]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

## 🔬 Deep Dive : np.corrcoef — correlation

```python
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([...])
np.corrcoef(salary, experience)
# → correlation matrix (1 diag, off-diag r)
```

- Pearson correlation coefficient matrix
- r ∈ [-1,1]: strength + direction
- r ≈ 1 positive strong, ≈ -1 negative, ≈ 0 none
- Interpretation: salary increases w/ experience?
- Matrix: [[var1_var1, var1_var2], [var2_var1, var2_var2]]
- r = cov(x,y)/(stdx*stdy)
- Data insight: feature relationships
- Pre ML: correlation screening
- Spearman: scipy alternative
- np.dot normalization manual possible

In [165]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [166]:
# code
a


array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

## 🔬 Deep Dive : np.isin — membership

```python
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a, items)]      # elements of a that are in items
```

- np.isin(a, b) — elementwise "is in" → bool mask
- filters array to those values present in b
- vectorized membership (like in but array)
- mask combine: a[mask]
- vs np.in1d (1D only) — isin general
- data subset by id list — common
- categorical filter bricks
- preserves order in a
- duplicates show multiple
- clean kwarg min_membership

In [168]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([50, 30])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [169]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

## 🔬 Deep Dive : np.flip — reverse

```python
np.flip(a)            # reverse all (1D)
np.flip(b, axis=1)    # reverse columns
```

- Reverse order along axis
- axis=0 rows, axis=1 cols, default all
- View (no copy) for 1D/trailing
- `a[::-1]` equivalent
- 2D flip = mirror
- Data ordering reverse (recent→older)
- Images: flip transformations
- keep dims; change sequence
- flipud/fliplr — up-down / left-right
- Useful augmentation data

In [170]:
np.flip(a)

array([21,  2, 78,  9, 68, 30,  5, 92, 94, 37, 38, 50, 28, 53, 11])

In [171]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [174]:
np.flip(b,axis=1)

array([[ 6, 42, 52, 12],
       [55, 47, 18, 29],
       [ 9, 83, 93, 61],
       [85, 44, 63, 38],
       [72, 31, 87,  8],
       [ 7,  2, 71, 40]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [192]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

## 🔬 Deep Dive : np.put — replace values

```python
np.put(a, [0,1], [110,530])    # set a[0]=110, a[1]=530
```

- put(indices, values) — replace at given flat indexes
- works on flattened view (flat index over all dims)
- indices list + values list
- a[0]=110 (flat pos 0), a[1]=530
- in place; repeats values if fewer
- mode 'clip'/'wrap' behavior
- vs assignment a[[0,1]] = [..]
- Useful filling specific positions
- limited by flat order (not axis)
- fast low-level assignment

In [193]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [178]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

## 🔬 Deep Dive : np.delete — remove elements

```python
np.delete(a, [0,2,4])    # remove positions 0,2,4 → new array
```

- Removes elements at given indices
- Returns new array (original intact)
- axis for multidim; default flatten
- Indices in flat order
- np.delete vs masking (mask preferred often)
- Removes, doesn't replace
- Gap: index list any subset
- Keep-filter `a[mask]` faster many cases
- Data cleaning drop indices
- attributes remain

In [181]:
np.delete(a,[0,2,4])

array([530,  50,  37,  94,  92,   5,  30,  68,   9,  78,   2,  21])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

## 🔬 Deep Dive : Set functions

```python
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m, n)        # ∪ all unique
np.intersect1d(m, n)    # ∩ common
np.setdiff1d(n, m)      # in n not m
np.setxor1d(m, n)       # symmetric diff
np.in1d(m, n)           # m elements in n (mask)
```

- Set algebra on arrays
- union — all values both
- intersect — common values
- setdiff1d(a,b) — in a not in b (order matters)
- setxor — exactly one
- in1d → membership mask
- Returned sorted unique
- Data dedupe/merge analysis
- pandas merge similar
- vectorized set ops

In [182]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [183]:
np.intersect1d(m,n)

array([3, 4, 5])

In [185]:
np.setdiff1d(n,m)

array([6, 7])

In [186]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [189]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [190]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

## 🔬 Deep Dive : np.clip — limit values

```python
np.clip(a, a_min=25, a_max=75)   # 25 ≤ val ≤ 75
```

- Clip values to range [min, max]
- Below min → min; above max → max
- a_min/a_max in order
- Outlier clipping (winsorization)
- Model outputs softmax no need
- input data scale bounds
- in-place variant: np.clip(out=)
- Gradient clipping concept
- data-safety transformation
- kwargs form notation common

In [191]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals